name: 'ski_weather'
version: '1.0.0'
config-version: 2

profile: 'ski_weather'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  ski_weather:
    staging:
      +materialized: view
    marts:
      +materialized: table
